"""Generates the ros_gz_bridge config from declared capabilities.

A hand-written bridge config needs an entry per camera and has to be edited
whenever the fleet changes, so it drifts from the topic names subscribers
actually use.  Here the bridge is derived from the same ``provides``
declarations that feed the manifest, so the two can never disagree.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml

from .adapter import Instance

GIMBAL_AXES = ("roll", "pitch", "yaw")


def entries_for(inst: Instance, world: str) -> list[dict[str, Any]]:
    caps = inst.vehicle.capabilities(name=inst.name, world=world)
    out: list[dict[str, Any]] = []
    for item in caps["sensors"] + caps["actuators"]:
        ros = item.get("ros")
        gz_topic = item.get("gz_topic")
        if not ros or not gz_topic:
            continue                      # onboard sensors the autopilot reads directly
        axes = item.get("axes") or [None]
        for axis in axes:
            gz = gz_topic.format(axis=axis) if axis else gz_topic
            ros_topic = ros["topic"].format(axis=axis) if axis else ros["topic"]
            out.append({
                "ros_topic_name": ros_topic,
                "gz_topic_name": gz,
                "ros_type_name": ros["type"],
                "gz_type_name": ros.get("gz_type", ""),
                "direction": ros.get("direction", "GZ_TO_ROS"),
            })
    return out


def build_config(instances: list[Instance], world: str, *, clock: bool = True) -> list[dict]:
    entries: list[dict[str, Any]] = []
    if clock:
        entries.append({
            "ros_topic_name": "/clock",
            "gz_topic_name": f"/world/{world}/clock",
            "ros_type_name": "rosgraph_msgs/msg/Clock",
            "gz_type_name": "gz.msgs.Clock",
            "direction": "GZ_TO_ROS",
        })
    for inst in instances:
        entries.extend(entries_for(inst, world))
    return entries


def write_config(instances: list[Instance], world: str, path: Path,
                 *, clock: bool = True) -> Path:
    entries = build_config(instances, world, clock=clock)
    path.parent.mkdir(parents=True, exist_ok=True)
    header = ("# GENERATED by uavsim -- do not edit.\n"
              f"# ros_gz_bridge config for world {world!r}, {len(instances)} vehicles.\n"
              "# ros2 run ros_gz_bridge parameter_bridge "
              f"--ros-args -p config_file:={path}\n")
    path.write_text(header + yaml.safe_dump(entries, sort_keys=False))
    return path
